feat: Customisation
theirc/UgandaTemplate pull request #8
Opened 2023-11-13 12:30 UTC by chamibia

2023-12-07 16:15 UTC, Guiso92 requested changes

2023-12-07 16:15 UTC, Guiso92 commented on next.config.js
> +  swcMinify: true,
why did this changed?

2023-12-07 16:22 UTC, chamibia commented on next.config.js
> +  swcMinify: true,
I'm not sure, i will update it though

2024-01-08 19:43 UTC, Guiso92 approved these changes

2024-01-08 22:27 UTC, merged